import type { RoomProduct, MealProduct, ActivityProduct } from "./types";

// Wilderness Edge Lodge - Mock Product Data

export const mockRooms: RoomProduct[] = [
  {
    id: "room-alpine-suite",
    name: "Alpine Suite",
    description: "Spacious suite with panoramic mountain views, king bed, and private balcony. Features a separate living area and luxury bathroom with rain shower.",
    imageUrl: "https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=600&h=400&fit=crop",
    pricePerNight: 320,
    currency: "CHF",
    tags: ["suite", "mountain-view", "balcony", "premium"],
    maxAdults: 2,
    maxChildren: 1,
    stock: 4,
  },
  {
    id: "room-forest-cabin",
    name: "Forest Cabin",
    description: "Cozy standalone cabin nestled among pine trees. Features a wood-burning fireplace, kitchenette, and private deck with forest views.",
    imageUrl: "https://images.unsplash.com/photo-1587061949409-02df41d5e562?w=600&h=400&fit=crop",
    pricePerNight: 280,
    currency: "CHF",
    tags: ["cabin", "fireplace", "private", "family"],
    maxAdults: 4,
    maxChildren: 2,
    stock: 6,
  },
  {
    id: "room-lakeside-lodge",
    name: "Lakeside Lodge Room",
    description: "Comfortable room in the main lodge overlooking the lake. Queen bed with premium linens and en-suite bathroom.",
    imageUrl: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=600&h=400&fit=crop",
    pricePerNight: 195,
    currency: "CHF",
    tags: ["lake-view", "lodge", "standard"],
    maxAdults: 2,
    maxChildren: 1,
    stock: 12,
  },
  {
    id: "room-family-chalet",
    name: "Family Chalet",
    description: "Two-bedroom chalet perfect for families. Master bedroom with queen bed, kids room with bunk beds, shared living space and full kitchen.",
    imageUrl: "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=600&h=400&fit=crop",
    pricePerNight: 420,
    currency: "CHF",
    tags: ["family", "chalet", "kitchen", "two-bedroom"],
    maxAdults: 4,
    maxChildren: 3,
    stock: 3,
  },
  {
    id: "room-treehouse",
    name: "Treehouse Retreat",
    description: "Unique elevated treehouse experience with glass walls, suspended deck, and a stargazing skylight. Double bed with luxury amenities.",
    imageUrl: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=600&h=400&fit=crop",
    pricePerNight: 350,
    currency: "CHF",
    tags: ["unique", "treehouse", "romantic", "premium"],
    maxAdults: 2,
    maxChildren: 0,
    stock: 2,
  },
  {
    id: "room-standard-double",
    name: "Standard Double",
    description: "Well-appointed standard room with double bed, work desk, and garden views. Perfect for solo travelers or couples.",
    imageUrl: "https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=600&h=400&fit=crop",
    pricePerNight: 145,
    currency: "CHF",
    tags: ["standard", "garden-view", "budget"],
    maxAdults: 2,
    maxChildren: 0,
    stock: 15,
  },
  {
    id: "room-glamping-tent",
    name: "Safari Glamping Tent",
    description: "Luxury canvas tent with real beds, wooden floors, and private outdoor shower. An immersive nature experience with all creature comforts.",
    imageUrl: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=600&h=400&fit=crop",
    pricePerNight: 175,
    currency: "CHF",
    tags: ["glamping", "outdoor", "unique", "adventure"],
    maxAdults: 2,
    maxChildren: 1,
    stock: 8,
  },
  {
    id: "room-penthouse",
    name: "Eagle's Nest Penthouse",
    description: "The crown jewel of Wilderness Edge. Wraparound terrace with 360-degree views, private hot tub, full kitchen, and premium concierge service.",
    imageUrl: "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=600&h=400&fit=crop",
    pricePerNight: 680,
    currency: "CHF",
    tags: ["penthouse", "hot-tub", "premium", "luxury", "concierge"],
    maxAdults: 4,
    maxChildren: 2,
    stock: 1,
  },
];

export const mockMeals: MealProduct[] = [
  {
    id: "meal-mountain-breakfast",
    name: "Mountain Breakfast Buffet",
    description: "Full breakfast buffet with local cheeses, fresh-baked bread, cold cuts, eggs to order, fresh fruits, and mountain herb teas.",
    pricePerPerson: 35,
    currency: "CHF",
    category: "breakfast",
    dietaryOptions: ["vegetarian", "gluten-free-options"],
  },
  {
    id: "meal-packed-lunch",
    name: "Trail Packed Lunch",
    description: "Hearty packed lunch for outdoor adventures. Includes artisan sandwiches, trail mix, fruit, and a drink.",
    pricePerPerson: 22,
    currency: "CHF",
    category: "lunch",
    dietaryOptions: ["vegetarian", "vegan-option"],
  },
  {
    id: "meal-lodge-dinner",
    name: "Lodge Dinner (3-Course)",
    description: "Three-course dinner in the main lodge restaurant. Seasonal menu featuring local Alpine cuisine with wine pairing option.",
    pricePerPerson: 65,
    currency: "CHF",
    category: "dinner",
    dietaryOptions: ["vegetarian", "vegan-option", "gluten-free-options"],
  },
  {
    id: "meal-bbq-evening",
    name: "Lakeside BBQ Evening",
    description: "Outdoor barbecue by the lake with grilled meats, fresh salads, corn on the cob, and campfire desserts.",
    pricePerPerson: 55,
    currency: "CHF",
    category: "dinner",
    dietaryOptions: ["vegetarian-option"],
  },
  {
    id: "meal-afternoon-tea",
    name: "Alpine Afternoon Tea",
    description: "Traditional afternoon tea with homemade scones, finger sandwiches, petit fours, and a selection of mountain herb infusions.",
    pricePerPerson: 28,
    currency: "CHF",
    category: "snack",
    dietaryOptions: ["vegetarian", "gluten-free-options"],
  },
];

export const mockActivities: ActivityProduct[] = [
  {
    id: "act-guided-hike",
    name: "Guided Mountain Hike",
    description: "Expert-led hike through scenic Alpine trails with breathtaking viewpoints. Suitable for moderate fitness levels.",
    imageUrl: "https://images.unsplash.com/photo-1551632811-561732d1e306?w=600&h=400&fit=crop",
    pricePerPerson: 45,
    currency: "CHF",
    durationMinutes: 240,
    maxParticipants: 12,
  },
  {
    id: "act-kayaking",
    name: "Lake Kayaking",
    description: "Explore the pristine mountain lake by kayak. Equipment and safety briefing included. No experience necessary.",
    imageUrl: "https://images.unsplash.com/photo-1472745433479-4556f22e32c2?w=600&h=400&fit=crop",
    pricePerPerson: 60,
    currency: "CHF",
    durationMinutes: 120,
    maxParticipants: 8,
  },
  {
    id: "act-rock-climbing",
    name: "Rock Climbing Adventure",
    description: "Indoor and outdoor climbing sessions with certified instructors. All skill levels from beginner to advanced.",
    imageUrl: "https://images.unsplash.com/photo-1522163182402-834f871fd851?w=600&h=400&fit=crop",
    pricePerPerson: 75,
    currency: "CHF",
    durationMinutes: 180,
    maxParticipants: 6,
  },
  {
    id: "act-wildlife-safari",
    name: "Wildlife Photography Safari",
    description: "Dawn wildlife safari with a professional nature photographer. Spot deer, eagles, marmots, and more in their natural habitat.",
    imageUrl: "https://images.unsplash.com/photo-1474511320723-9a56873571b7?w=600&h=400&fit=crop",
    pricePerPerson: 90,
    currency: "CHF",
    durationMinutes: 300,
    maxParticipants: 8,
  },
  {
    id: "act-spa-wellness",
    name: "Alpine Spa & Wellness",
    description: "Full day access to the thermal spa, sauna complex, and relaxation areas. Includes one 30-minute massage treatment.",
    imageUrl: "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=600&h=400&fit=crop",
    pricePerPerson: 120,
    currency: "CHF",
    durationMinutes: 480,
    maxParticipants: 20,
  },
  {
    id: "act-cooking-class",
    name: "Alpine Cooking Class",
    description: "Learn traditional Swiss mountain cuisine from our head chef. Prepare and enjoy a 4-course meal with local ingredients.",
    imageUrl: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=600&h=400&fit=crop",
    pricePerPerson: 85,
    currency: "CHF",
    durationMinutes: 180,
    maxParticipants: 10,
  },
];

export const mockData = {
  rooms: mockRooms,
  meals: mockMeals,
  activities: mockActivities,
};
